require:
  - rubocop-rails
  - rubocop-performance

Layout/ClassStructure:
  Enabled: true

Layout/LineLength:
  Max: 80
  Exclude:
    - 'config/**/*'
    - 'db/seeds.rb'
    - 'app/jobs/application_job.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

AllCops:
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'Rakefile'

